services:
  diun:
    container_name: diun
    command: serve
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - TZ=Pacific/Auckland
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 0 * * FRI
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_NOTIF_SLACK_WEBHOOKURL=$DIUN_NOTIF_SLACK_WEBHOOKURL
      - DIUN_NOTIF_SLACK_RENDERFIELDS=true

    labels:
      - diun.enable=true
    restart: always
    image: crazymax/diun:latest

  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/danieldbird/Dockers/frigate/config:/config/config.yaml
      - /home/danieldbird/Dockers/frigate/storage:/media/frigate
    ports:
      - 5000:5000
      - 1935:1935
    environment:
      FRIGATE_RTSP_PASSWORD: $FRIGATE_RTSP_PASSWORD

  ntp-server:
    container_name: ntp-server
    restart: always
    read_only: true
    ports:
      - '123:123/udp'
    tmpfs:
      - /etc/chrony:rw,mode=1750
      - /run/chrony:rw,mode=1750
      - /var/lib/chrony:rw,mode=1750
    image: cturra/ntp
    environment:
      NTP_SERVERS: '0.nz.pool.ntp.org,1.nz.pool.ntp.org,2.nz.pool.ntp.org,3.nz.pool.ntp.org'
